name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: docker build . -t rampunit/react-cicd
    - run: echo "${{secrets.DOCKERHUB_PASSWORD}}" | docker login -u ${{secrets.DOCKERHUB_USERNAME}} --password-sdin
    - run: docker push rampunit/react-cicd:latest