name: Deploy to Hostinger Subdomain

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Build and deploy
        env:
          HOSTINGER_FTP_HOST: ${{ secrets.HOSTINGER_FTP_HOST }}
          HOSTINGER_FTP_USERNAME: ${{ secrets.HOSTINGER_FTP_USERNAME }}
          HOSTINGER_FTP_PASSWORD: ${{ secrets.HOSTINGER_FTP_PASSWORD }}
          SUBDOMAIN: subdomain
        run: |
          npm run build
          gh-pages -d build -r $HOSTINGER_FTP_HOST -u $HOSTINGER_FTP_USERNAME -p $HOSTINGER_FTP_PASSWORD -s $SUBDOMAIN
