name: Deploy to Hostinger Subdomain

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run build
      - name: Deploy via FTP
        env:
          HOSTINGER_FTP_HOST: ${{ secrets.HOSTINGER_FTP_HOST }}
          HOSTINGER_FTP_USERNAME: ${{ secrets.HOSTINGER_FTP_USERNAME }}
          HOSTINGER_FTP_PASSWORD: ${{ secrets.HOSTINGER_FTP_PASSWORD }}
          SUBDOMAIN: ${{ secrets.SUBDOMAIN }}
        run: |
          apt-get update && apt-get install -y lftp
          lftp -e "mirror -R build /public_html/${SUBDOMAIN}; quit" -u $HOSTINGER_FTP_USERNAME,$HOSTINGER_FTP_PASSWORD $HOSTINGER_FTP_HOST
